import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
import SessionProvider from "@/components/SessionProvider"; // 1. Додали імпорт

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-[#050505] text-white antialiased`}
        suppressHydrationWarning
      >
        {/* 2. Обгортаємо все в SessionProvider, щоб Navbar мав доступ до сесії */}
        <SessionProvider>
          <Provider>
            <Navbar />
            
            <main className="container mx-auto pt-4">
              {children}
            </main>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}